### ISSUE TITLE
Error detected while processing function <SNR>58_UseConfigFiles..

### ISSUE THREAD

**Issue by janbaer** [editorconfig/editorconfig-vim#47] opened 2015-11-15 08:58 UTC
When I load a file from a directory that contains an .editorconfig file I get the following error from your vim-plugin:

Error detected while processing function <SNR>58_UseConfigFiles..<SNR>58_UseConfigFiles_Python_Builtin:
line   33:
Traceback (most recent call last):
  File "<string>", line 3, in <module>
TypeError: expected string without null bytes

My **.editorconfig** looks like the following snippet

```
root = true

[*]
indent_style = space
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

Do you've an idea how to fix the problem?

**Comment by xuhdev** [comment] 2015-11-17 00:08
@janbaer I think we need a few more information in this case...

- What is your OS?
- What is the output of `:version`?
- What is your version of Python?
- Are you using the latest version of the plugin?

**Comment by janbaer** [comment] 2015-11-19 18:06
It's as MacOS 10.11, I've python 2.7 and 3.5 installed and that's the output of :version

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 29 2015 11:31:46)
MacOS X (unix) version
Included patches: 1-769
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +cryptv          +find_in_path    +lispindent      +mouse_urxvt     +quickfix        +tcl             +wildmenu
+arabic          +cscope          +float           +listcmds        +mouse_xterm     +reltime         +terminfo        +windows
+autocmd         +cursorbind      +folding         +localmap        +multi_byte      +rightleft       +termresponse    +writebackup
+balloon_eval    +cursorshape     -footer          -lua             +multi_lang      +ruby            +textobjects     -X11
+browse          +dialog_con_gui  +fork()          +menu            -mzscheme        +scrollbind      +title           -xfontset
++builtin_terms  +diff            +fullscreen      +mksession       +netbeans_intg   +signs           +toolbar         +xim
+byte_offset     +digraphs        -gettext         +modify_fname    +odbeditor       +smartindent     +transparency    -xsmp
+cindent         +dnd             -hangul_input    +mouse           +path_extra      -sniff           +user_commands   -xterm_clipboard
+clientserver    -ebcdic          +iconv           +mouseshape      +perl            +startuptime     +vertsplit       -xterm_save
+clipboard       +emacs_tags      +insert_expand   +mouse_dec       +persistent_undo +statusline      +virtualedit     -xpm
+cmdline_compl   +eval            +jumplist        -mouse_gpm       +postscript      -sun_workshop    +visual
+cmdline_hist    +ex_extra        +keymap          -mouse_jsbterm   +printer         +syntax          +visualextra
+cmdline_info    +extra_search    +langmap         +mouse_netterm   +profile         +tag_binary      +viminfo
+comments        +farsi           +libcall         +mouse_sgr       +python          +tag_old_static  +vreplace
+conceal         +file_in_path    +linebreak       -mouse_sysmouse  -python3         -tag_any_white   +wildignore
```

And yes, I installed your plugin with vundle directly from github from the master branch

**Comment by xuhdev** [comment] 2015-11-19 21:57
I cannot reproduce this bug... Did you upgrade your Python version recently? If so, can you run `brew reinstall macvim` (or `vim`)?

Also, is the python from homebrew or OS X?

**Comment by alexlrobertson** [comment] 2015-12-08 22:05
I get the same issue regardless of wether the file is in a directory the contains an `.editorconfig` file.

* OS X 10.11.1
* Python 2.7.11

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 30 2015 09:17:39)
MacOS X (unix) version
Included patches: 1-944
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
```

**Comment by xuhdev** [comment] 2015-12-08 23:37
@alexlrobertson Can you provide some information in my previous comment, please? I asked about Python installation because this kind of bug reports often come up shortly after a Homebrew Python update.

**Comment by alexlrobertson** [comment] 2015-12-09 15:16
The issue appeared when I upgraded my Python version via Homebrew.

I reinstalled vim and updated the editorconfig-vim plugin via Vundle and it looks to be working now. Thanks for the help.

**Comment by jviotti** [comment] 2018-07-07 05:04
@xuhdev I'm hitting the same issue. I'm using MacVim and Python@2 from Homebrew, and the Homebrew Python (2.7.15) was taking precedence over macOS's Python (2.7.10), but giving precedence to the latter in the PATH didn't fix the issue. Reinstalling MacVim didn't help either.

**Comment by jviotti** [comment] 2018-07-07 05:06
Interestingly enough, the problem is gone if I use macOS's vim rather than MacVim.

This is my system's vim:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 29 2017 18:37:46)
Included patches: 1-503, 505-680, 682-1283
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             +comments        +extra_search    -keymap          -mouse_dec       +path_extra      +smartindent     +timers          -X11
-arabic          -conceal         -farsi           +lambda          -mouse_gpm       -perl            +startuptime     +title           -xfontset
+autocmd         +cryptv          +file_in_path    -langmap         -mouse_jsbterm   +persistent_undo +statusline      -toolbar         -xim
-balloon_eval    +cscope          +find_in_path    +libcall         -mouse_netterm   +postscript      -sun_workshop    +user_commands   -xpm
-browse          +cursorbind      +float           +linebreak       -mouse_sgr       +printer         +syntax          +vertsplit       -xsmp
+builtin_terms   +cursorshape     +folding         +lispindent      -mouse_sysmouse  -profile         +tag_binary      +virtualedit     -xterm_clipboard
+byte_offset     +dialog_con      -footer          +listcmds        -mouse_urxvt     +python/dyn      +tag_old_static  +visual          -xterm_save
+channel         +diff            +fork()          +localmap        +mouse_xterm     -python3         -tag_any_white   +visualextra
+cindent         +digraphs        -gettext         -lua             +multi_byte      +quickfix        -tcl             +viminfo
-clientserver    -dnd             -hangul_input    +menu            +multi_lang      +reltime         -termguicolors   +vreplace
-clipboard       -ebcdic          +iconv           +mksession       -mzscheme        -rightleft       -terminal        +wildignore
+cmdline_compl   -emacs_tags      +insert_expand   +modify_fname    +netbeans_intg   +ruby/dyn        +terminfo        +wildmenu
+cmdline_hist    +eval            +job             +mouse           +num64           +scrollbind      +termresponse    +windows
+cmdline_info    +ex_extra        +jumplist        -mouseshape      +packages        +signs           +textobjects     +writebackup
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa
```

And this is MacVim:

```
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 30 2018 01:47:01)
macOS version
Included patches: 1-72
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +comments          +file_in_path      +libcall           -mouse_sysmouse    -python            +tcl               +vreplace
+arabic            +conceal           +find_in_path      +linebreak         +mouse_urxvt       +python3           +termguicolors     +wildignore
+autocmd           +cryptv            +float             +lispindent        +mouse_xterm       +quickfix          +terminal          +wildmenu
-autoservername    +cscope            +folding           +listcmds          +multi_byte        +reltime           +terminfo          +windows
+balloon_eval      +cursorbind        -footer            +localmap          +multi_lang        +rightleft         +termresponse      +writebackup
+balloon_eval_term +cursorshape       +fork()            -lua               -mzscheme          +ruby              +textobjects       -X11
+browse            +dialog_con_gui    +fullscreen        +menu              +netbeans_intg     +scrollbind        +timers            -xfontset
++builtin_terms    +diff              -gettext           +mksession         +num64             +signs             +title             +xim
+byte_offset       +digraphs          -hangul_input      +modify_fname      +odbeditor         +smartindent       +toolbar           -xpm
+channel           +dnd               +iconv             +mouse             +packages          +startuptime       +transparency      -xsmp
+cindent           -ebcdic            +insert_expand     +mouseshape        +path_extra        +statusline        +user_commands     -xterm_clipboard
+clientserver      +emacs_tags        +job               +mouse_dec         +perl              -sun_workshop      +vertsplit         -xterm_save
+clipboard         +eval              +jumplist          -mouse_gpm         +persistent_undo   +syntax            +virtualedit
+cmdline_compl     +ex_extra          +keymap            -mouse_jsbterm     +postscript        +tag_binary        +visual
+cmdline_hist      +extra_search      +lambda            +mouse_netterm     +printer           +tag_old_static    +visualextra
+cmdline_info      +farsi             +langmap           +mouse_sgr         +profile           -tag_any_white     +viminfo
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_
FORTIFY_SOURCE=1
Linking: clang   -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr
/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -L.
             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib
-L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib  -L/usr/local/lib -o Vi
m -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2leve
l/CORE -lperl  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation -F/Sys
tem/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby
```

**Comment by jviotti** [comment] 2018-07-07 05:08
Hm, I'm seeing the following main difference when it comes to Python:

macOS vim:

```
+python/dyn
-python3
```

MacVim:

```
-python
+python3
```

I don't know about Python, so this might be a long shot, but maybe MacVim is trying to run this module with Python 3, and therefore it fails?

**Comment by jviotti** [comment] 2018-07-07 05:19
@xuhdev Looks like this was definitely the issue. After taking a look into `brew info macvim`, I rebuilt MacVim against Python 2 (`brew reinstall macvim --with-python@2`), and voilà! Everything works fine now :) Thanks for the module!

**Comment by cxw42** [comment] 2020-06-09 12:52
Closing because it sounds like this has been resolved --- please feel free to comment back and reopen if you are still having this problem with the latest plugin (1.1.1).

**Closed by cxw42** 2020-06-09 12:52 UTC
