### ISSUE TITLE
Wrong reading order

### ISSUE THREAD

**Issue by wernight** [editorconfig/editorconfig-vim#40] opened 2015-06-30 10:17 UTC
From http://editorconfig.org/#file-format-details the `.editorconfig` should be read from top to bottom, each time overriding previous setting. This can be inferred from their example: "closest EditorConfig files are read last [...] so properties in closer files take precedence."

````
EditorConfig files are read top to bottom and the closest EditorConfig files are read last. Properties from matching EditorConfig sections are applied in the order they were read, so properties in closer files take precedence.
````

However this doesn't seem to be respected:

````
[*]
indent_style = tab

[*.md]
indent_style = space
indent_size = 4
````

Editing a `*.md` file would still apply tabs as indentation.

**Comment by sixbytestring** [comment] 2015-06-30 12:05
I'm also seeing this behaviour. Example file:

```ini
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
trim_trailing_whitespace = true

[*.go]
indent_style = tab
tab_width = 4
```

**Comment by xuhdev** [comment] 2015-06-30 17:36
Are you sure this is simply a wrong reading order, or your configuration isn't  loaded at all?

**Comment by wernight** [comment] 2015-06-30 20:30
I just changed and it reflects, so it's read, just wrongly interpreted a far as I can tell.

**Comment by xuhdev** [comment] 2015-06-30 21:27
Can you run the following command and paste the output?

    python /path/to/editorconfig-vim/plugin/editorconfig-core-py/main.py /path/to/your.md

**Comment by wernight** [comment] 2015-06-30 21:35
`.editorconfig`
````
# editorconfig.org
root = true

[*]
indent_style = space
indent_size = 4
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
indend_style = tab
````

`python ~/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/main.py $PWD/README.md`
````
indent_style=space
indent_size=4
trim_trailing_whitespace=true
insert_final_newline=true
indend_style=tab
tab_width=4
````

**Comment by xuhdev** [comment] 2015-06-30 21:46
What is your location of your `.editorconfig`?

**Comment by xuhdev** [comment] 2015-06-30 22:11
Any way, this seems to be an issue of the EditorConfig python core (and I cannot reproduce your issue), because the core library does not return a correct configuration. Can you post the issue to [EditorConfig python core](https://github.com/editorconfig/editorconfig-core-py/issues)?

**Comment by xuhdev** [comment] 2015-06-30 22:13
There is also a workaround is to install the C EditorConfig core, and set `g:EditorConfig_core_mode = 'external_command'` to circumvent the Python library.

**Comment by sixbytestring** [comment] 2015-07-01 10:19
@xuhdev I'm not so sure this is actually an editorconfig-core-py issue; I've done some digging and found some more useful info.

Basically, it looks like editorconfig-vim is making use of `indent_size` over a the combination of `tab_width` and `indent_style` if set. Example:

```ini
[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
trim_trailing_whitespace = true

[*.go]
indent_style = tab
tab_width = 4

[*.md]
trim_trailing_whitespace = false
```

Will reproduce the issue; tabbing in a Go file will result in two spaces initially, with a further tab resulting in a 4-space wide tab. But simply adding `indent_size = 4` under the `[*.go]` section will correct the behaviour.

So it seems to be a rule prioritisation / implementation issue within editorconfig-vim, unless I'm mistaken on the rules outlined in the EditorConfig standard?

**Comment by xuhdev** [comment] 2015-07-01 18:33
@sixbytestring Your case is intended, different from the original bug report. Some projects use a larger tab size than their indentation size, e.g. you may have a 8 tab size but 4 indentation size, so the code format like this:

    int hello()
    {
    <4-space>if (x)
    <1 tab>do someting
    }

Examples projects are Vim, gcc.

**Comment by wernight** [comment] 2015-07-02 09:39
Is it an issue with editorconfig-core? The elements it return seem correct supposing they are interpreted:

````
indent_style=space  # :set et
...
indend_style=tab  # :set noet
tab_width=4  # set sw=4 ts=4
````

If I do that manually, it would give the correct configuration. However if `sw` < `ts` then it would not work for example.

**Comment by ZoogieZork** [comment] 2015-07-02 16:13
@wernight Is this a typo?

    indend_style=tab

("inden_d_" instead of "inden_t_")?

**Comment by xuhdev** [comment] 2015-07-02 16:31
`tab_width = 4` sets `ts=4` only. `indent_size` decides `sw`.

**Comment by wernight** [comment] 2015-07-02 19:20
@xuhdev Oh!!! ***** That might be the reason. So it would have been switching between default and the global one. I tried again without the typo and couldn't get it to reproduce, so it should be it.

It's all my fault. There could be a typo warning, either from the most common, or safer, if Levenshtein distance if just 1 or 2 to any known and handled `.editorconfig` then show a warning.

I'm not really good at Vim scripting but I wouldn't mind to make a function in Python that does that. That would mean editorconfig-core I guess but how would it be ingested... I'll see with them if they have some idea.

**Comment by xuhdev** [comment] 2015-07-02 22:53
OK, since you have opened a new issue, can we close this issue up?

**Closed** 2015-07-05 05:42 UTC

**Comment by wernight** [comment] 2015-07-06 08:37
Ok, should there be another ticket to use https://github.com/editorconfig/utilities/tree/master/check-typos ?

**Comment by xuhdev** [comment] 2015-07-06 18:06
@wernight What do you mean? I thought the script would resolve editorconfig/editorconfig#224 and thus this issue.

**Comment by wernight** [comment] 2015-07-07 09:24
Shouldn't editorconfig-vim run this script and show an alert automatically?

**Comment by xuhdev** [comment] 2015-07-07 19:30
@wernight I don't think so, as you can extend properties by yourself. See `:h EditorConfig#AddNewHook()`

**Comment by wernight** [comment] 2015-07-08 07:24
Ok. Thanks
