### ISSUE TITLE
DeprecationWarning: the imp module is deprecated

### ISSUE THREAD

**Issue by thenoseman** [editorconfig/editorconfig-vim#109] opened 2018-07-04 13:16 UTC
Hi,

I get this error when opening a project where editorconfig-vim triggers:

```
Error detected while processing function <SNR>94_UseConfigFiles[26]..<SNR>94_Initialize[47]..<SNR>94_InitializePythonBuiltin:
line   23:
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

My `:version`:
```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  4 2018 08:18:18)
macOS version
Included patches: 1-139
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +clientserver      +dialog_con_gui    +find_in_path      +jumplist          +mksession         +mouse_xterm       +postscript        +smartindent       +terminfo          +visual            -xpm
+arabic            +clipboard         +diff              +float             +keymap            +modify_fname      +multi_byte        +printer           +startuptime       +termresponse      +visualextra       -xsmp
+autocmd           +cmdline_compl     +digraphs          +folding           +lambda            +mouse             +multi_lang        +profile           +statusline        +textobjects       +viminfo           -xterm_clipboard
-autoservername    +cmdline_hist      +dnd               -footer            +langmap           +mouseshape        -mzscheme          -python            -sun_workshop      +timers            +vreplace          -xterm_save
+balloon_eval      +cmdline_info      -ebcdic            +fork()            +libcall           +mouse_dec         +netbeans_intg     +python3           +syntax            +title             +wildignore
+balloon_eval_term +comments          +emacs_tags        +fullscreen        +linebreak         -mouse_gpm         +num64             +quickfix          +tag_binary        +toolbar           +wildmenu
+browse            +conceal           +eval              -gettext           +lispindent        -mouse_jsbterm     +odbeditor         +reltime           +tag_old_static    +transparency      +windows
++builtin_terms    +cryptv            +ex_extra          -hangul_input      +listcmds          +mouse_netterm     +packages          +rightleft         -tag_any_white     +user_commands     +writebackup
+byte_offset       +cscope            +extra_search      +iconv             +localmap          +mouse_sgr         +path_extra        +ruby              +tcl               +vartabs           -X11
+channel           +cursorbind        +farsi             +insert_expand     -lua               -mouse_sysmouse    +perl              +scrollbind        +termguicolors     +vertsplit         -xfontset
+cindent           +cursorshape       +file_in_path      +job               +menu              +mouse_urxvt       +persistent_undo   +signs             +terminal          +virtualedit       +xim
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/Users/user/.rbenv/versions/2.4.2/lib  -fstack-protector -L/usr/local/lib -L. -L/Users/user/.rbenv/versions/2.4.2/lib  -fstack-protector -L/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon
  -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m
-framework CoreFoundation -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -lruby-static -framework CoreFoundation -lgmp -lobjc -L/Users/user/.rbenv/versions/2.4.2/lib
```

Python used:
```
> ❯ /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/bin/python3.7 --version
Python 3.7.0
```

I really don't know python so sorry for just dumping the "bug" here and not supplying a PR :)

Thanks!

**Comment by k-takata** [comment] 2018-07-04 13:50
duplicate of #108

**Closed** 2018-07-04 17:11 UTC
